### ISSUE TITLE
Extension manager marks all extensions as incompatible, even if they're supported in the latest gnome

### ISSUE THREAD

**Issue by r0xANDt0l** [Vanilla-OS/testing-issues#39]
This happens no matter if the system is on ro or rw

**Comment by mirkobrombin** [comment]
I'm facing the same bug with latest build but version is correct
![image](https://user-images.githubusercontent.com/9479903/206130174-9cfafa5a-84ef-407b-a4ca-beb6bbaa7796.png)

extensions.gnome.org and the extensions manager does not works. This is very weird since FWIK the extensions manager takes the GNOME version from D-Bus which is right:

![image](https://user-images.githubusercontent.com/9479903/206130466-9d835961-b7cb-4295-8b3f-887391a44eea.png)

**Comment by mirkobrombin** [comment]
Fixed by https://github.com/Vanilla-OS/vanilla-base-meta/commit/40c62bde0c5441b4a720ea1dce90be792f66501f
